### ISSUE TITLE
The nDCG formula may not consistent between your paper and implementation?

### ISSUE THREAD

**Issue by yuukiyamanaka** [chenchongthu/ENMF#7]
Hello, I read your paper(TOIS) and your implementation.
I have a question about your implementation of the formula of nDCG.

In your paper, you write the formula of nDCG using log2 (logarithmic base is 2), but in your implementation I think you use np.log (logarithmic base is natural logarithm). (c.g., L209 or L303 in code/ENMF.py)

Should you use np.log2 in your implementation for consistency?

Anyway, thank you for putting together a good paper and implementation!

**Comment by chenchongthu** [comment]
This is a very easy transformation:

logM N=loga M/loga N

**Comment by yuukiyamanaka** [comment]
opps, I understand. Thank you.
