### ISSUE TITLE
想请问下您有没有考虑实现过非负采样+lightGCN这样的模型呢？实验效果会比MF为基础模型好吗？

### ISSUE THREAD

**Issue by saladcat** [chenchongthu/ENMF#8]

**Comment by chenchongthu** [comment]
尝试过，效果会相比于lightGCN有些许提升，但是提升幅度不如BPRMF->非采样MF。我们AAAI 2021 的工作 https://github.com/chenchongthu/GHCF 就是在GCN类模型上使用非采样进行模型训练~

**Comment by saladcat** [comment]
感谢您的回复，非常精彩和有深度的工作，谢谢
